### ISSUE TITLE
decorator chains

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#110]
**Migrated issue, originally created by Tudor Aursulesei ([thestick](https://github.com/thestick))**

how does dogpile.cache's cache_on_arguments handle a decorated class method? What if the second decorator contains some fixed args and kwargs? Which of these is put in the key? I've had to deal with this and the second decorator doesn't have the functools.wrap magic attached so it confuses dogpile.cache - i received wrong cache data.

I've added a namespace and everything seems to work. Is this expected? How can i prevent this in the future in a safer way?

**Comment by zzzeek** [comment]
what's being described here seems kind of complicated and I'd need an example to play with, unless someone else has a clearer idea how to illustrate specifics.
