### ISSUE TITLE
pymemcache support

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/dogpile.cache#134]
an old PR that never got completed is at https://bitbucket.org/zzzeek/dogpile.cache/pull-requests/34/this-gives-initial-support-for-pymemcache/diff, but also there seems to be more interest in this backend: https://review.openstack.org/#/c/616304/ .

**Comment by zzzeek** [comment]
I've adapted the PR at https://gerrit.sqlalchemy.org/#/c/sqlalchemy/dogpile.cache/+/947/

**Comment by zzzeek** [comment]
cc @morganfainberg , needs a few more tweaks

**Comment by zzzeek** [comment]
there seems to be no interest in this right now.   contributors feel free to reopen + implement.

**Comment by zzzeek** [comment]
OK we have a PR at #197

**Comment by sqla-tester** [comment]
**Moisés Guimarães de Medeiros** has proposed a fix for this issue in the **master** branch:

**Add pymemcache backend** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2494
