### ISSUE TITLE
redis cluster support? / add pifpaf for redis cluster to tox.ini

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/dogpile.cache#135]
we have a gerrit at:  

https://gerrit.sqlalchemy.org/#/c/sqlalchemy/dogpile.cache/+/950

however, we have no support for running a redis cluster to see if this works at all.

See if we can add another pifpaf directive to run a redis with a cluster configuration file, as we see at https://redis.io/topics/cluster-tutorial.   I haven't looked carefully yet but it seems like we just make an extra config file and some directories, stuff we can do in a shell script along side tox.ini, then just start redis with that config.

**Comment by jvanasco** [comment]
This should probably run two Redis instances in cluster mode, both can be on `127.0.0.1`.

**Comment by zzzeek** [comment]
this can be reopened if someone wants to work on it.

**Comment by jvanasco** [comment]
We will be running dogpile under PY2 for the foreseeable future, so it won't be me :(
