### ISSUE TITLE
Suggestion for a better dogpile lock for the DBMBackend

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/dogpile.cache#141]
Hello, I was reading the documentation of DBMBackend.get_mutex and it states the following:
```python
    def get_mutex(self, key):
        # using one dogpile for the whole file.   Other ways
        # to do this might be using a set of files keyed to a
        # hash/modulus of the key.   the issue is it's never
        # really safe to delete a lockfile as this can
        # break other processes trying to get at the file
        # at the same time - so handling unlimited keys
        # can't imply unlimited filenames
```
I understand the issue here, and I would like to propose an implementation that uses only one lock file but allows to lock `sys.maxint` different keys.
The idea is to use a lock file and use `fcntl` locking operations using the range options.

This would be a raw implementation of the `RangedFileLock class`:
```python
def get_position(key, max=sys.maxint):
    # Map any string to randomly distributed integers between 0 and max
    hash = hashlib.sha1(key).digest()
    return int(codecs.encode(hash, 'hex'), 16) % max


class RangedFileLock(AbstractFileLock):
    """Use lockfiles to coordinate read/write access to a file.

    Only works on Unix systems, using
    `fcntl.flock() <http://docs.python.org/library/fcntl.html>`_.

    """

    def __init__(self, filename, key):
        self.key_offset = get_position(key)    # Line changed
        self._filedescriptor = compat.threading.local()
        self.filename = filename

    @util.memoized_property
    def _module(self):
        import fcntl
        return fcntl

    @property
    def is_open(self):
        return hasattr(self._filedescriptor, 'fileno')

    def acquire_read_lock(self, wait):
        return self._acquire(wait, os.O_RDONLY, self._module.LOCK_SH)

    def acquire_write_lock(self, wait):
        return self._acquire(wait, os.O_WRONLY, self._module.LOCK_EX)

    def release_read_lock(self):
        self._release()

    def release_write_lock(self):
        self._release()

    def _acquire(self, wait, wrflag, lockflag):
        wrflag |= os.O_CREAT
        fileno = os.open(self.filename, wrflag)
        try:
            if not wait:
                lockflag |= self._module.LOCK_NB
            self._module.lockf(fileno, lockflag, 1, self.key_offset)  # Line changed
        except IOError:
            os.close(fileno)
            if not wait:
                # this is typically
                # "[Errno 35] Resource temporarily unavailable",
                # because of LOCK_NB
                return False
            else:
                raise
        else:
            self._filedescriptor.fileno = fileno
            return True

    def _release(self):
        try:
            fileno = self._filedescriptor.fileno
        except AttributeError:
            return
        else:
            self._module.lockf(fileno, self._module.LOCK_UN, 1, self.key_offset)  # Line changed
            os.close(fileno)
            del self._filedescriptor.fileno
```
I am aware that this would only work on Unix systems (if I understand correctly), but `FileLock` class is not supporting other systems anyway for the time being.
The benefit of using this strategy with respect to the one suggested in the docstring of `get_mutex` is that we won't even need to have many files on the file system, and there is not need to having file deletion routines.

I would like to know your opinion on this, and if you think it's a good approach I'll start with a PR.

**Comment by zzzeek** [comment]
this seems like an amazing idea if it works.   we could just have this lock as an option in any case, right?

**Comment by youtux** [comment]
Indeed this must be a new option, because `flock` and `lockf` use two different lock systems, at least on linux (see http://man7.org/linux/man-pages/man2/flock.2.html#NOTES).

**Comment by youtux** [comment]
I am also working on an implementation of a FileSystem lock that does not use a DBM file and that allows to get and set files directly without the need of loading the content in memory, but I don't quite understand the reason of wrapping the dogpile lock file with `KeyReentrantMutex.factory`:
```python
self._dogpile_lock = self._init_lock(
            arguments.get('dogpile_lockfile'),
            ".dogpile.lock",
            dir_, filename,
            util.KeyReentrantMutex.factory)
```
@zzzeek can you help me with this?

**Comment by zzzeek** [comment]
the mutexes want to be in a registry based on a name, so that one lock that is locking on "foo" doesn't have to contend with another lock locking on "bar", and additionally it is reentrant because people want to be able to access the cache from within a function that is itself cached.

there seems to be some API weirdness in that the wrapper is changing the behavioral contract of self._dogpile_lock to be a key-based callable.   but if we switch it with a "null" factory:

```diff
diff --git a/dogpile/cache/backends/file.py b/dogpile/cache/backends/file.py
index 309c055..56320a2 100644
--- a/dogpile/cache/backends/file.py
+++ b/dogpile/cache/backends/file.py
@@ -148,7 +148,7 @@ class DBMBackend(CacheBackend):
             arguments.get('dogpile_lockfile'),
             ".dogpile.lock",
             dir_, filename,
-            util.KeyReentrantMutex.factory)
+            lambda mutex: lambda key: mutex)
 
         # TODO: make this configurable
         if compat.py3k:

```

then run py.test tests/cache/test_dbm_backend.py and it quickly hits tests that deadlock.

**Comment by youtux** [comment]
So in case of mutexes that lock exclusively on a key (e.g. `RedisBackend.get_mutex(key)`) then there is no need of wrapping it with KeyReentrantMutex, while mutexes that do not have a 1:1 correspondence with the key (e.g. `DBMBackend.get_mutex(key)` since it uses 1 master lock) should be wrapped with KeyReentrantMutex, is that right?

**Comment by zzzeek** [comment]
I believe that is correct yes.

**Comment by youtux** [comment]
Also, the mutex returned by DBMBackend.get_mutex() in the current code cannot be (reliably) given to an async_creation_runner like a celery job, since the mutex can only be held by the process that created it.
Is there any requirement for these Mutex objects? I see quite inconsistent behavior across the backends.

**Comment by zzzeek** [comment]
in the case of async_creation_runner, if you're handing off a lock from one process to another it's kind of assumed you would know to use a distributed lock object, like a redis lock or something like that.      when you say "requirement" you refer to the scope of the lock, right?  (single process, multi process, multi host) ?    these scopes generally conform to the type of backend being used.   if you're using a "memory" backend, there's no need to use a cross-process lock, for example.   if you wanted to use DBM with an async runner being passed off to celery youd want to plug in a compatible lock object.

**Comment by youtux** [comment]
I recently published the backend as a dogpile cache plugin at https://github.com/paylogic/dogpile_filesystem.
