### ISSUE TITLE
behavioral change since decorator switch

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/dogpile.cache#144]
This test case raises ValueError prior to 0.7.0's switch to [decorator](https://gerrit.sqlalchemy.org/#/c/sqlalchemy/dogpile.cache/+/996/):

```
from dogpile.cache import make_region

region = make_region().configure(
    'dogpile.cache.memory',
)

@region.cache_on_arguments()
def load_user_info(value=0):
    return "hi"

# passes now, used to raise 
# ValueError: dogpile.cache's default key creation function does not accept keyword arguments.
print(load_user_info(value=5))
```

Additionally, it raises TypeError instead of ValueError when an invalid kw is passed.    

I think we need to restore the old behavior here (edit: I think it's fine) because the key generation function should be seeing the args passed in the same way.

**Comment by zzzeek** [comment]
cc @ankitpatel96

**Comment by zzzeek** [comment]
welp, let's look more closely, and look at the argspec:

```
from dogpile.cache import make_region

region = make_region().configure(
    'dogpile.cache.memory',
)


def load_user_info(value=0):
    return "hi"

import inspect

print(inspect.getfullargspec(load_user_info))


load_user_info = region.cache_on_arguments()(load_user_info)


print(inspect.getfullargspec(load_user_info))

print(load_user_info(value=5))
```

with current 0.7.1, we get:
```

FullArgSpec(args=['value'], varargs=None, varkw=None, defaults=(0,), kwonlyargs=[], kwonlydefaults=None, annotations={})
FullArgSpec(args=['value'], varargs=None, varkw=None, defaults=(0,), kwonlyargs=[], kwonlydefaults=None, annotations={})

```

which is, perfect.  old behavior, we blew them away.  so that's kind of what's happening here:

```
FullArgSpec(args=['value'], varargs=None, varkw=None, defaults=(0,), kwonlyargs=[], kwonlydefaults=None, annotations={})
FullArgSpec(args=[], varargs='arg', varkw='kw', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})

```

if you want to see the ValueError again, need to pass kw like this:
```

def load_user_info(value=0, **kw):
    return "hi"

import inspect

print(inspect.getfullargspec(load_user_info))


load_user_info = region.cache_on_arguments()(load_user_info)


print(inspect.getfullargspec(load_user_info))

print(load_user_info(value=5, foo=7))
```


So I think this is all good.   Need to talk to downstream oslo.cache in https://bugs.launchpad.net/oslo.cache/+bug/1817032 .

**Comment by 4383** [comment]
For more informations on the openstack/oslo.cache side:
http://lists.openstack.org/pipermail/openstack-discuss/2019-February/003196.html

**Comment by zzzeek** [comment]
keeping the new behavior for now after clarification.

**Comment by 4383** [comment]
I've adapt my oslo.cache patch by following your approach https://review.openstack.org/#/c/638788/8

**Comment by 4383** [comment]
@zzzeek Thanks for time :)

**Comment by ankitpatel96** [comment]
thanks for taking care of this @zzzeek

**Comment by zzzeek** [comment]
we'll add a test

**Comment by sqla-tester** [comment]
**Hervé Beraud** has proposed a fix for this issue in the **master** branch:

**Adding tests to check behavioral changes introduced by decorator** https://gerrit.sqlalchemy.org/1144
