### ISSUE TITLE
cache.cache_on_arguments() stopped working

### ISSUE THREAD

**Issue by millerthegorilla** [sqlalchemy/dogpile.cache#149]
I've been using dogpile.cache for a project which uses a rest api to populate a list based on a dropdown selection, using pyqt.
Recently, I was forced to reinstall, and when I had finished doing so, the cache_on_arguments decorator had stopped working.  I've tried everything that I can think of and it still won't work.  When I use the decorator the method is not entered.
I noticed that there had been some recent changes to the code, so I changed my code to create the cache region in the file listing the class.  I am decorating a method of a class, but have tried moving the method to the file level, ie outside of the class, to no avail.
I am using the dbm backend, and have tried using a set of different permission sets on the file.
Everything was working fine, and I had made no changes to that section of code, so I am now tearing my hair out.  Perhaps I am missing a dependency on reinstalling?  I wouldn't have thought so, since I am using pycharm, and installed dogpile.cache into the venv using the settings.  Dependencies should have been called in when installing.  I tried a different backend and the same issue.
Any helpful suggestions much appreciated.

**Comment by zzzeek** [comment]
are you able to determine the exact versions of all software in use both before and after the reinstall?    try force installing dogpile.cache 0.6.8, as a lot of folks have had to adjust to some decorator behavior introduced in 0.7.0.

**Comment by millerthegorilla** [comment]
Thanks, but it doesn't work still.  I had tried reverting to version 0.7.0, but with no luck, and have just tried reverting to 0.6.8, cleared the caches and restarted, and no luck.  I also tried reverting my refactor, and not luck.
When I comment out the decorator, the function is entered.  When I don't comment it out, the function is not entered.
Is there any way to debug dogpile?

**Comment by zzzeek** [comment]
you can debug it using pdb or other interactive debugger.

**Comment by millerthegorilla** [comment]
thanks, I'll have a go now.

**Comment by millerthegorilla** [comment]
I'm not entirely sure how I had dogpile.core installed but I did.  Once I uninstalled it I got an error :

    error: db type could not be determined

I am guessing that the way I create the cache file is wrong.  I have simply used touch on the file so far.  I tried a bunch of different permissions.  Do you know if there is a required permission set for a db file, or a cachefile creation method that I am missing?
Many thanks.

**Comment by millerthegorilla** [comment]
Aha.  I should have left the make region function to create the cache file.  Its all working now.  Thanks!
