### ISSUE TITLE
dogpile.cache keeps data after invalidation

### ISSUE THREAD

**Issue by Rogalek** [sqlalchemy/dogpile.cache#156]
So, I am building web application and had some problems with functional tests. During my test I am changing value of my setting which I am keeping in cache. I am using redis and Postgres as my databases.

    class SettingService(object):

    def __init__(self, request):
        self.request = request
        self.session = request.session

    @region_1month.cache_on_arguments()
    def get_setting(self, key):
        return self.session.query(Setting)\
            .filter(Setting.key == key)\
            .first()

    def add_setting(self, key, value):
        setting_object = Setting(
            key=key,
            value=value
        )
        self.session.add(setting_object)
        self.session.flush()
        return setting_object

    def update_setting(self, setting_obj, value):
        setting_obj.value = value
        self.dbsession.add(setting_obj)
        self.dbsession.flush()
        self.get_setting.invalidate(None, setting_obj.key)
        return setting_obj

As you can see after updating setting cache should be invalidated and new value should occur. So when I am doing my test I am updating setting value, making request for my application and before it goes to the view it checks validation, setting still has old value and my tests fail.

Can you help me? If more code necessary I can provide it.

**Comment by zzzeek** [comment]
have you tried using print statements or pdb to ensure that "key" is what you expect it to be as well as ensuring that your get_setting() is called again? did you try removing the cache decorator?  etc.   is this a pyramid application?

**Comment by Rogalek** [comment]
1. Yes I have tried pdb or pycharm debugger with breakpoints to see step by step what happens. In test setting value is changed but when it goes to the view resource get_setting() shows old value.
2. Yes I removed cache decorator and it did not work - which makes me thing that is not fault of dogpile.cache now. 
3. Yes, this is pyramid application

So somehow problem was with something else.. I had to make `transaction.commit()` after each `update_setting` in the test..

**Comment by zzzeek** [comment]
OK, since this is pyramid, feel free to ask for more help on the pyramid mailing list.  As removing the cache decorator didn't affect the issue that seems to indicate this isn't a dogpile issue.  Feel free to reopen if you think there's an issue, thanks!
