### ISSUE TITLE
How cached values update to databases

### ISSUE THREAD

**Issue by tmacjx** [sqlalchemy/dogpile.cache#158]
Hello, I recent use redis to cache sqlchemy query result.

	class BaseModel(db.Model):
    	@classmethod
    	def from_dict(cls, data):
                 if not isinstance(data, dict):
                    data = dict(data)
                 return cls(**data)
		
when I get data from cache  I will use BaseModel.from_dict method to 
covert dict type data to Model instance, and then do some update operating.
	 
	 	cache_data =  {'id': 1, 'name': 'abc'}
	 	instance = Model(cache_data)
	 	instance.name = 'efg'
	 	db.session.commit()
		
	
It will raise Duplicate PRIMARY key?
		
Any Advice to me?
So sorry, Google and stackoverflow not see any advice.
THK A LOT!

**Comment by zzzeek** [comment]
hi there -

this seems like more of a sqlalchemy question, and while you aren't showing what you're doing, I'm assuming you are putting this object in the session using session.add().  For caching, you need to use [session.merge(obj, load=False)](https://docs.sqlalchemy.org/en/13/orm/session_api.html?highlight=session%20merge#sqlalchemy.orm.session.Session.merge) or .  See the get_value() method at https://docs.sqlalchemy.org/en/13/_modules/examples/dogpile_caching/caching_query.html which uses a similar merge() method on the Query object.

**Comment by tmacjx** [comment]
thanks a lot!
