### ISSUE TITLE
Does anyone already have a working mongodb backend?

### ISSUE THREAD

**Issue by thestick613** [sqlalchemy/dogpile.cache#161]
Hello,

Is there any reason we can't use mongodb as a backend?

**Comment by zzzeek** [comment]
you can write a custom backend per the guidelines at https://dogpilecache.sqlalchemy.org/en/latest/usage.html#creating-backends .    not sure if there is one already but I bet some people have them in-house.

**Comment by thestick613** [comment]
Well, if anyone else is interested, please check out #162 .
