### ISSUE TITLE
License mixup

### ISSUE THREAD

**Issue by AbdealiJK** [sqlalchemy/dogpile.cache#177]
Hi, I saw that the license in the current repository is MIT
Also, I found a older commit: https://github.com/sqlalchemy/dogpile.cache/commit/00d912c5892ba9cdce354493cf57595c8ac5833c
which changes the pypi classifiers to MIT

But the license being reported to pypi is still BSD:
https://github.com/sqlalchemy/dogpile.cache/blob/1ef1b7b3b29556f0fee987736cb8428fb333e39c/setup.py#L51

I assume that needs to be changed to MIT too ?

**Comment by zzzeek** [comment]
that would be because we have not released since october.   looks like there's some things to go out so will do that now.

**Comment by zzzeek** [comment]
fixed
