### ISSUE TITLE
dogpile.cache 1.0.0 cannot be installed on Python 3.5 because stevedore requires 3.6+

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/dogpile.cache#184]
Trying to install dogpile.cache in a `python:3.5` docker image yields the following error:

```
root@3b09b5b38442:/# pip install dogpile.cache
Collecting dogpile.cache
  Using cached dogpile.cache-1.0.0.tar.gz (339 kB)
Collecting decorator>=4.0.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
ERROR: Could not find a version that satisfies the requirement stevedore>=3.0.0 (from dogpile.cache) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.9, 0.9.1, 0.10, 0.11, 0.12, 0.13, 0.14, 0.14.1, 0.15, 1.0.0.0a2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.18.0, 1.19.0, 1.19.1, 1.20.0, 1.20.1, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.26.0, 1.27.0, 1.27.1, 1.28.0, 1.29.0, 1.30.0, 1.30.1, 1.31.0, 1.32.0)
ERROR: No matching distribution found for stevedore>=3.0.0 (from dogpile.cache)
```

**Comment by zzzeek** [comment]
well we probably have to bump dogpile.cache to 3.6 then, no mystery there.     cc @dhellmann

**Comment by dhellmann** [comment]
You could use conditional requirements to specify a different version of stevedore for older dogpile.cache.

Something like:

```
stevedore>=2.0.0,<3.0.0; python_version<'3.6'
stevedore>=3.0.0; python_version>='3.6'
```

**Comment by zzzeek** [comment]
Why don't we just make the requirement "stevedore>=2.0.0" across the board?  if they are on a newer python they will get the newer stevedore unless they have an old version still lying around, in which case, that still works they just have fewer features.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Lower stevedore minimum version to 2.0.0** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2101

**Comment by RazerM** [comment]
stevedore 2.0 can't be installed on 3.5 either. I don't mind if dogpile.cache 1.0.1 requires 3.6, but could you yank 1.0.0 once it's released so that pip will install 0.9.2 on Python 3.5?

**Comment by zzzeek** [comment]
guess we have to do that too.

**Comment by zzzeek** [comment]
so we will pin to 3.6 but I also have to figure out how to do #185

**Comment by zzzeek** [comment]
what's the difference between "yank" and "delete" on Pypi?  I did a yank.

**Comment by RazerM** [comment]
yank doesn’t prevent pip installing that exact version when requested, but it won’t choose that version on its own. I.e. 3.6 users who pinned 1.0.0 can keep using it and 3.5 users who didn’t pins version will get 0.9.2
