### ISSUE TITLE
py2.py3 wheel created with 1.0.0 version

### ISSUE THREAD

**Issue by AdarShaked** [sqlalchemy/dogpile.cache#185]
Hi 
Seems that 1.0.0 version is not py2 compatible but this flag:

https://github.com/sqlalchemy/dogpile.cache/blob/master/setup.cfg#L45

Cause pip wheel generate py2py3 wheel.
Maybe this is not the problem but pip wheel generation py2.py3 wheel and its wrong  :)

**Comment by zzzeek** [comment]
Ok aloing with #184 this needs to be done for 1.0.1 release

**Comment by AdarShaked** [comment]
Thanks
