### ISSUE TITLE
egg fragments resolution

### ISSUE THREAD

**Issue by itd** [sqlalchemy/dogpile.cache#194]
I'm getting  errors when trying to install dogpile.cache 

It seems similar to a PEP-517 packaging issue I found here:
https://github.com/pypa/packaging-problems/issues/252#issuecomment-483878594

Here's a snippet of the -vv output:
```
Collecting dogpile.cache==1.0.2
  Using cached dogpile.cache-1.0.2.tar.gz (351 kB)
  WARNING: Generating metadata for package dogpile.cache produced metadata for project name unknown. Fix your #egg=dogpile.cache fragments.
Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/53/05/f8445598250e0237aeaf0d82301f56ee5550b7d4d24dcdd44c7425c50497/dogpile.cache-1.0.2.tar.gz#sha256=64fda39d25b46486a4876417ca03a4af06f35bfadba9f59613f9b3d748aa21ef in ./venvstack/lib/python3.6/site-packages (from -r req.txt (line 15))

  Attempting uninstall: setuptools
    Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

openstacksdk 0.48.0 requires dogpile.cache>=0.6.5, which is not installed.
python-ironicclient 4.2.0 requires dogpile.cache>=0.6.2, which is not installed.```

**Comment by zzzeek** [comment]
hi there -

In #178 we made sure we are not doing anything even slightly non-standard in response to upstream/downstream issues.   I have no insight on this issue and I am not familiar with any source code in dogpile.cache itself which can cause problems with installation, so I would recommend reaching out to the pypa community to get help from this issue.  We can make *further* adjustments as they are able to recommend.

**Comment by itd** [comment]
I just tried it on 4 other systems os/distro combinations and could not reproduce this issue, so it has to be an issue local to a specific installation/problem on one of my servers. Thanks for the quick feedback!
