### ISSUE TITLE
Threading related deprecation warnings in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [sqlalchemy/dogpile.cache#203]
Python 3.10 deprecates camelCase aliases in threading module. 

Ref : python/cpython#25174 

notifyAll -> notify_all
currentThread -> current_thread

```
dogpile/util/readwrite_lock.py
65:                # yes. so if a sync operation is waiting, notifyAll to wake
68:                    self.condition.notifyAll()
98:            self.current_sync_operation = threading.currentThread()
120:            if self.current_sync_operation is not threading.currentThread():
```

**Comment by zzzeek** [comment]
thanks!  are these names in python 3.6?  that's our bottom version right now.   I would assume they are.

**Comment by sqla-tester** [comment]
**Karthikeyan Singaravelan** has proposed a fix for this issue in the **master** branch:

**Fix DeprecationWarning due to camelCase aliases in Python 3.10.** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2840

**Comment by sqla-tester** [comment]
**Karthikeyan Singaravelan** has proposed a fix for this issue in the **master** branch:

**Fix DeprecationWarning due to camelCase aliases in Python 3.10.** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2840
