### ISSUE TITLE
How to cache raws sql with dogpile 

### ISSUE THREAD

**Issue by mwaaas** [sqlalchemy/dogpile.cache#206]
am trying to do db.session.execute and the query is not cached. but db.session.query is cached. 

This is because on session creation I have replaced it with Custom query that does cache with dogpile 

Is there away to do for db.session.execute

**Comment by zzzeek** [comment]
hi -

when using SQLAlchemy 1.4 there is a new version of the dogpile caching system that uses the [do_orm_execute](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=do_orm_execute#sqlalchemy.orm.SessionEvents.do_orm_execute) event.   Assuming your recipe came from the examples/dogpile.cache recipe in SQLAlchemy, please adjust your code to use the new approach documented at https://docs.sqlalchemy.org/en/14/orm/examples.html#module-examples.dogpile_caching
