### ISSUE TITLE
Custom Serializer ?

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#21]
**Migrated issue, originally created by jvanasco ([jvanasco](https://github.com/jvanasco))**

As I look at expanding a project with increasing components ( Pyramid Web + Twisted Daemons + (sadly) PHP ), interoperability is becoming a bit of a concern.

Looking through the backends:

file.py

* serializes - util.pickle.dumps(value)
* deserialze - util.pickle.loads(value)
* [ util.pickle is cPickle or pickle ]
 
memcached.py

* serializes & deserialize are handled within the various 3rd party modules ( largely pickle )

memory

* native storage

redis.py

* serializes - pickle.dumps(value)
* deserialze - pickle.loads(value)
* [ pickle is dogpile.cache.util's pickle ]

Would you consider a patch that does the following:

* CacheRegion accepts a 'SerializationAPI' object
* the SerializationApi has two methods - `serialize` and `deserialize`
* the 'SerializationApi' defaults to the current behavior ( pickle )
* one could create a custom scheme and pass it in ( ie, json or something else )

While I don't think this would do much for the memcached libraries ( though some are looking at the same custom serialization options ), it would allow the file-backed dbm/ndbm and redis backends to be more interoperable.

**Comment by tmacjx** [comment]
Does dogpile support json? I see default Serializer is pickle

**Comment by zzzeek** [comment]
> Does dogpile support json? I see default Serializer is pickle

this issue is a dupe of #18.     for the moment you have to write a custom backend to override "pickle" for redis.  For memcached, the memcached clients bake in pickle but might skip it if you pass them a string.
