### ISSUE TITLE
redis has changed their lock API in a backwards incompatible fashion

### ISSUE THREAD

**Issue by rsgmon** [sqlalchemy/dogpile.cache#220]
I'm using the Redis backend and basically copied the code from the module in sqlalchemy that contains the CachingQuery class. However I am using manual keys. 

With the following configuration I get the intermittent error in subject line. 

`regions["default"] = make_region(key_mangler=md5_key_mangler).configure(
    "dogpile.cache.redis",
    expiration_time=3600,
    arguments={
        "host": config["redis"].get("host"),
        "redis_expiration_time": 60 * 60 * 2,
        "distributed_lock": True,
        "thread_local_lock": False,
    },
)`

Here's the code where it occurs:

`
      
        _async = False
        if self._has_value(createdtime):

            has_value = True

        -->   if not self.mutex.acquire(False):

                log.debug("creation function in progress elsewhere, returning")

                return NOT_REGENERATED

        else:

            has_value = False

            log.debug("no value, waiting for create lock")`

Any suggestions would be appreciated.

**Comment by zzzeek** [comment]
I would need to see a complete stack trace

**Comment by rsgmon** [comment]
`  File "foundation/list/mixins.py", line 60, in get_state_list_item_by_name
    .filter(ListItem.name == state_list_item_name)
  File "sqlalchemy/orm/query.py", line 2979, in first
    ret = list(self[0:1])
  File "sqlalchemy/orm/query.py", line 2771, in __getitem__
    return list(res)
  File "foundation/caching_query.py", line 64, in __iter__
    return self.get_value(createfunc=lambda: list(super_.__iter__()))
  File "foundation/caching_query.py", line 138, in get_value
    cache_key, createfunc, expiration_time=expiration_time
  File "dogpile/cache/region.py", line 1047, in get_or_create
    async_creator,
  File "dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "dogpile/lock.py", line 126, in _enter_create
    if not self.mutex.acquire(False):`

**Comment by rsgmon** [comment]
`File "foundation/list/mixins.py", line 60, in get_state_list_item_by_name
  .filter(ListItem.name == state_list_item_name)

File "sqlalchemy/orm/query.py", line 2979, in first
  ret = list(self[0:1])

File "sqlalchemy/orm/query.py", line 2771, in __getitem__
  return list(res)

File "foundation/caching_query.py", line 64, in __iter__
  return self.get_value(createfunc=lambda: list(super_.__iter__()))

File "foundation/caching_query.py", line 138, in get_value
  cache_key, createfunc, expiration_time=expiration_time

File "dogpile/cache/region.py", line 1047, in get_or_create
  async_creator,

File "dogpile/lock.py", line 185, in __enter__
  return self._enter()

File "dogpile/lock.py", line 94, in _enter
  generated = self._enter_create(value, createdtime)

File "dogpile/lock.py", line 126, in _enter_create
  if not self.mutex.acquire(False):`

**Comment by zzzeek** [comment]
redis has been releasing in recent weeks and they changed this API to be positional only (even though I think main Python API is positional only, will check)

**Comment by zzzeek** [comment]
they changed the API in release 4.3.2

https://github.com/redis/redis-py/commit/fa0be7671de6be85f859cbb57a31531b2482c9e1#r75610569

**Comment by jvanasco** [comment]
FYI, It looks like Redis took over that project from https://github.com/andymccurdy sometime in the past 2 years.  The original maintainer was often focused on API stability.

**Comment by zzzeek** [comment]
yeah....OK let me just run dogpile main in jenkins and we can close this

**Comment by zzzeek** [comment]
it's still wrong

**Comment by zzzeek** [comment]
https://github.com/redis/redis-py/issues/2223

submitter please pin to py-redis 4.3.1 until they fix this

**Comment by rsgmon** [comment]
ok thanks, updated to `"redis==4.3.1",`
