### ISSUE TITLE
Feature request: support socket_timeout and dead_retry in memcached backend

### ISSUE THREAD

**Issue by freedge** [sqlalchemy/dogpile.cache#223]
Right now memcached backend only support a limited number of arguments.
It was noticed a while ago through https://bugs.launchpad.net/oslo.cache/+bug/1723133 that notably dead_retry and socket_timeout were not implemented.

Downstream, oslo.cache already fills the arguments dictionary with values for dead_retry and socket_timeout, but dogpile.cache ignore them so the defaults (of 30s for dead_retry and 3s for socket_timeout) are used. In fact oslo.cache [believes](https://github.com/openstack/oslo.cache/blob/master/oslo_cache/_opts.py#L91) it is setting a 300s dead_retry and 1s socket timeout, but of course this is not happening.

I would wish for dogpile.cache to support socket_timeout and dead_retry in memcached backend.

**Comment by zzzeek** [comment]
we can go with a PR that is done in the same style as the patch I just pushed out in https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/3916  - to each memcached backend add connection_kwargs and that will accommodate for all additional keywrod arguments received by each memcached connection routine.
