### ISSUE TITLE
Releasing a new version of dogpile.cache

### ISSUE THREAD

**Issue by 4383** [sqlalchemy/dogpile.cache#227]
Hey @zzzeek,

Is it possible to release a new version of dogpile.cache?

We recently identified an issue between [1] openstack keystone and the latest changes [2] of dogpile.cache. The deadline for the milestone 2 of the Openstack Z series is next week (July 14) [3] so it would be useful to release these changes soon to let's time to see if other side effects are detected in other openstack services and so let's time to fix them before the final release of the Z series.

Thanks by advance.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2103117
[2] https://github.com/sqlalchemy/dogpile.cache/commit/1de93aab14c1274f20c1f44f8adff3b143c864f6
[3] https://releases.openstack.org/zed/schedule.html#z-2

**Comment by zzzeek** [comment]
OK will get this by tomorrow

**Comment by 4383** [comment]
All my previous local tests against keystone, keystonemiddleware and oslo.cache worked without issues even with the latest fix.

**Comment by zzzeek** [comment]
OK 1.1.7 is released

**Comment by 4383** [comment]
Thank you Mike
