### ISSUE TITLE
Get last refresh time

### ISSUE THREAD

**Issue by riyadparvez** [sqlalchemy/dogpile.cache#231]
Is it possible to find out when a cache item is last refreshed? Similar to `cached_func.refresh(arg1)` function we can add `cached_func.last_refresh_time(arg1)`?

**Comment by zzzeek** [comment]
the creation time for the value is in the metadata like this

```py
from dogpile.cache import make_region

region = make_region().configure(
    'dogpile.cache.memory',
    expiration_time = 3600,
)

region.set("my_key", 10)

raw_not_serialized = region._get_from_backend("my_key")
creation_time = raw_not_serialized.metadata["ct"]


```

**Comment by jvanasco** [comment]
Mike answered while I was writing the below, but...

There is an example of this in the docs using the core directly: https://dogpilecache.sqlalchemy.org/en/latest/core_usage.html

You can also accomplish this by using a custom (de)serializer (see https://dogpilecache.sqlalchemy.org/en/latest/api.html?highlight=loads#dogpile.cache.region.CacheRegion.params.serializer) - or ProxyBackend (see https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.proxy.ProxyBackend) to change the returned value into an object that has this metadata accessible.

When doing so, the CachedValue is a namedtuple - see https://github.com/sqlalchemy/dogpile.cache/blob/main/dogpile/cache/api.py#L104-L116 - consisting of a `(Value, Metadata)`, and the "creation time" is the "ct" key in metadata.
