### ISSUE TITLE
Add py.typed marker

### ISSUE THREAD

**Issue by Daverball** [sqlalchemy/dogpile.cache#238]
It looks like dogpile does use type annotations internally, is there a reason why they are not being exported? The package needs to include a `py.typed` marker file for mypy to recognize that it may use the type annotations, otherwise it will treat the package as untyped.

**Comment by zzzeek** [comment]
seems like an oversight if this is the case.  PRs welcome

**Comment by sqla-tester** [comment]
**Daverball** has proposed a fix for this issue in the **main** branch:

**Add py.typed marker and include it in package data** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4624
