### ISSUE TITLE
`CacheRegion.configure` should return `typing_extensions.Self`

### ISSUE THREAD

**Issue by Daverball** [sqlalchemy/dogpile.cache#240]
https://github.com/sqlalchemy/dogpile.cache/blob/96b8b2858f29c44893257b2487fd38554d4346ef/dogpile/cache/region.py#L429

Returning a fixed type here is unfriendly to subclassing `CacheRegion` to e.g. add new methods.

**Comment by Daverball** [comment]
Before that it would've still been possible using `def method(self: _T) -> _T:` But I agree that it is a little bit more cumbersome to use a `TypeVar`.

**Comment by zzzeek** [comment]
to clarify, pep-673 provides the `Self` type.  this code should be changed as follows:

```diff
diff --git a/dogpile/cache/region.py b/dogpile/cache/region.py
index 79f7eaa..952f245 100644
--- a/dogpile/cache/region.py
+++ b/dogpile/cache/region.py
@@ -18,6 +18,7 @@ from typing import Sequence
 from typing import Tuple
 from typing import Type
 from typing import Union
+from typing_extensions import Self
 
 from decorator import decorate
 
@@ -426,7 +427,7 @@ class CacheRegion:
         wrap: Sequence[Union[ProxyBackend, Type[ProxyBackend]]] = (),
         replace_existing_backend: bool = False,
         region_invalidator: Optional[RegionInvalidationStrategy] = None,
-    ) -> "CacheRegion":
+    ) -> Self:
         """Configure a :class:`.CacheRegion`.
 
         The :class:`.CacheRegion` itself
diff --git a/setup.cfg b/setup.cfg
index 319c4b9..3efb2ce 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -24,6 +24,7 @@ project_urls =
 install_requires =
   decorator>=4.0.0
   stevedore>=3.0.0
+  typing_extensions
 zip_safe = False
 packages = find:
 python_requires = >=3.6

```

**Comment by sqla-tester** [comment]
**Viicos** has proposed a fix for this issue in the **main** branch:

**Use `typing.Self`** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4739

**Comment by sqla-tester** [comment]
**Viicos** has proposed a fix for this issue in the **main** branch:

**Use `typing.Self`** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4739
