### ISSUE TITLE
RedisBackend URL also overrides password

### ISSUE THREAD

**Issue by ericli-splunk** [sqlalchemy/dogpile.cache#245]
The documentation says `url` will override "host/port/db" params
https://github.com/sqlalchemy/dogpile.cache/blob/221c6fe7b9375c6534eb4f606dffdfc5d126d3b7/dogpile/cache/backends/redis.py#L47

However actually it also overrides the "password" param
https://github.com/sqlalchemy/dogpile.cache/blob/221c6fe7b9375c6534eb4f606dffdfc5d126d3b7/dogpile/cache/backends/redis.py#L145

Is it possible to update the documentation? Thanks.

**Comment by zzzeek** [comment]
sure, please send a pull request.  thanks

**Comment by ericli-splunk** [comment]
Created #246

**Comment by sqla-tester** [comment]
**Eric Li** has proposed a fix for this issue in the **main** branch:

**Update RedisBackend documentation** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/4904
