### ISSUE TITLE
Cross platform file caching

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#44]
**Migrated issue, originally created by Anonymous**

I'm looking for a cross platform file caching backend as the dogpile.cache.backends.file requires fcntl which is Unix.
In my case I'll have a single thread doing rw operations so I don't mind not having a rw lock.

* It should be mentioned in the docs that the file backend is not compatible with Windows in a more explicit way
* The file backend should be cross platform
* The file backend should have an optional rw lock

**Comment by razsteinmetz** [comment]
Hi,
Any chance this will ever work on windows?

**Comment by zzzeek** [comment]
> Hi,
> Any chance this will ever work on windows?

I've just re-read this issue and it seems to indicate that everything works on windows.  as described in https://github.com/sqlalchemy/dogpile.cache/issues/44#issuecomment-441401014 and in the docs at https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.backends.file.DBMBackend you would use your win32 locking library of choice and plug it in using the [lock_factory](https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.backends.file.DBMBackend.params.lock_factory) parameter.

**Comment by razsteinmetz** [comment]
I agree, but I would suggest to mention it in the documentation (or at least in the opening example) - it will save the time to figure it out from the error message.  Just my 10cents....
