### ISSUE TITLE
Path to cache backend not always works

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#68]
**Migrated issue, originally created by Victor Varvaryuk ([warvariuc](https://github.com/warvariuc))**

[dogpile.cache / dogpile / cache / util.py](https://bitbucket.org/zzzeek/dogpile.cache/src/1c753914b335b4391bc5847a87b7c52ca81c2bc6/dogpile/cache/util.py?at=master):
```
#!python

    def register(self, name, modulepath, objname):
        def load():
            mod = __import__(modulepath)
            for token in modulepath.split(".")[1:]:
                mod = getattr(mod, token)
            return getattr(mod, objname)
        self.impls[name] = load
```
This way of getting the object doesn't work if the module on `modulepath` is not fully imported yet and there is no the corresponding module attribute at top level module.

This should work for all cases:

```
#!python

    def register(self, name, modulepath, objname):
        def load():
            mod = __import__(modulepath, fromlist=[objname])
            return getattr(mod, objname)
        self.impls[name] = load
```

**Comment by zzzeek** [comment]
this was fixed in e9bc5a0a90ed38e9581f3d80ef477888415d1e91
