### ISSUE TITLE
Globally prefix all redis keys

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#70]
**Migrated issue, originally created by Gustavo Carneiro ([gjcarneiro](https://github.com/gjcarneiro))**

Hi, I would like dogpile to prefix all keys it puts into redis with a string given by me.  For instance, it now creates keys like

"api.db:get_customer_balance|2933"

I want to prefix everything with a string, like "mymodule:dogpile:".

I found a way to do this, using the key_mangler, but it I'm not sure if it's the appropriate use for it.  If it is appropriate, could you add some words in the documentation explaining this use case?  Thanks.

**Comment by zzzeek** [comment]
this is something the key_mangler does right now, we can accept some docs if someone wants to contribute.
