### ISSUE TITLE
Option to ignore exceptions (e.g. ConnectionError)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#72]
**Migrated issue, originally created by Mihnea Dobrescu-Balaur ([mihneadb](https://github.com/mihneadb))**

It would be useful to have a parameter for when configuring a region such that exceptions are silenced. Since we are talking about a cache, the application should still run even if the cache dies - putting try except everywhere in the code where one uses caching is too much.
A global flag that decides to silence the exceptions or not would do this job.

**Comment by zzzeek** [comment]
we haven't really had other calls for this feature, although if someone can provide a recipe we can put it up on the site.
