### ISSUE TITLE
File size bloat when anydbm picks gdbm

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#90]
**Migrated issue, originally created by David Gardner ()**

This might not be a dogpile cache bug, but ran into this and thought you should be aware of it.

When using the dogpile.cache.dbm disk backend if the anydbm picks the gdbm implementation, then the dbm disk file will continue to grow. The reason seems to be that gdbm requires that [gdbm.reorganize](https://docs.python.org/2/library/gdbm.html#gdbm.reorganize) is called periodically while none of the other dbm backends have this method.

----------------------------------------
Attachments: [gdbm-repro.py](../wiki/imported_issue_attachments/90/gdbm-repro.py)

**Comment by zzzeek** [comment]
hopefully gdbm is not in common usage now, closing
